# Generated by Django 5.1 on 2024-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=70)),
                ('nick_name', models.CharField(max_length=70, unique=True)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
