"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ndby!w&-ru+m^_q280qam$@lobqoy97^q@3^p56^0ey*j+@ex'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'user_app',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Exemplo para React em desenvolvimento
    "http://localhost:8000",
    "http://localhost:8001",
    "https://flashvibe.vercel.app",
    "https://projeto-tg-back-end.onrender.com",
    "https://flashvibe.onrender.com"             # Seu domínio em produção
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    "http://localhost:8001",
    "https://flashvibe.vercel.app",
    "https://projeto-tg-back-end.onrender.com",
    "https://flashvibe.onrender.com"  # Adicione a versão HTTPS, se aplicável
]

CORS_ALLOW_HEADERS = [
    'jwt_token',  # Permitindo o jwt_token
    'Authorization',
    'session',  # Se você usa Authorization também
    'Content-Type'  # Outros cabeçalhos comuns
]

CORS_ORIGIN_WHITELIST = [
    'https://flashvibe.onrender.com',
    "http://localhost:3000",
    "http://localhost:8000"  # Adicione o domínio do seu frontend aqui
]

ROOT_URLCONF = 'setup.urls'

REST_FRAMEWORD = {'DEFAULT_PERMISSION_CLASSES': [
    'rest_frameword.permissions.AllowAny'
]}

# SECURE_SSL_REDIRECT = True

# # HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 3600  # 1 hora
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Protege cookies em conexões seguras
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# email credential for sending email

EMAIL_HOST = HOST_EMAIL = os.getenv("HOST_EMAIL")
EMAIL_HOST_USER = EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_PORT = PORT_EMAIL = os.getenv("PORT_EMAIL")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_BACKEND = CONNECTION_EMAIL = os.getenv("CONNECTION_EMAIL")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.models.backends.sqlite3'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432', cast=int),
        'OPTIONS': {
            'ssl': {
                'ca': './ca.pem',
            },
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
